services:
  nginx:
    image: nginx:alpine
    container_name: neurovault_gateway
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/api_conf.d:/etc/nginx/api_conf.d:ro
      - ./infra/nginx/api_backends.conf:/etc/nginx/api_backends.conf:ro
      - ./infra/nginx/api_gateway.conf:/etc/nginx/api_gateway.conf:ro
      - ./infra/nginx/api_json_errors.conf:/etc/nginx/api_json_errors.conf:ro
      - ./infra/nginx/cors.conf:/etc/nginx/cors.conf:ro
    networks:
      - neurovault_network

networks:
  neurovault_network:
    driver: bridge
