location /api/file/ {
    proxy_pass http://neurovault_file_handling;
    # Policy configuration here (authentication, rate limiting, logging...)
    access_log /var/log/nginx/fileHandling_api.log main;

    return 404; # Any URIs that do not match above will be handled by outer location
}