location /api/search/ {
    proxy_pass http://neurovault_search;
    # Policy configuration here (authentication, rate limiting, logging...)
    access_log /var/log/nginx/search_api.log main;

    return 404;
}